export const GET_STREAMS_START = 'GET_STREAMS_START';
export const GET_STREAMS_SUCCESS = 'GET_STREAMS_SUCCESS';
export const GET_STREAMS_ERROR = 'GET_STREAMS_ERROR';
export const GET_USERS_STREAMS_SUCCESS = 'GET_USERS_STREAMS_SUCCESS';
export const GET_USER_STREAMS_START = 'GET_USER_STREAMS_START';
export const GET_USER_STREAMS_ERROR = 'GET_USER_STREAMS_ERROR';
