services:
  frontend:
    build: ./
    container_name: frontend
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    # environment:
    #   - BROWSER=none
